function PARAMS = nscan_loadpar7(TXTFILE,varargin)
%NSCAN_LOADPAR7 - Load a parameter file of Curry7(Neuroscan).
%  PARAMS = NSCAN_LOADPAR7(TXTFILE,...) loads a parameter file of Curry7(neuroscain).
%  This function reads a parameter file (text) and converts 
%  some string parameters into numerics.
%
%  EXAMPLE :
%    dap = nscan_loadpar7('D:/Temp/Acquire 01.dap');
%    rs3 = nscan_loadpar7('D:/Temp/Acquire 01.rs3');
%    ceo = nscan_loadpar7('D:/Temp/Acquire 01.ceo');
%
%  VERSION :
%    0.90 23.01.14 YM  pre-release, MPI Tuebingen
%    0.91 10.02.14 YM  clean-up
%
%  See also nscan_loadtxt nscan_strconv nscan_loaddat7

%  COPYRIGHT (C) 2014 Yusuke Murayama,  Max Planck Institute for Biological Cybernetics
%  Simplified BSD License, see readme.txt for detail.


if nargin < 1, eval(['help ' mfilename]); return;  end

if ~exist(TXTFILE,'file'),
  error(' ERROR %s : ''%s'' not found.\n',mfilename,TXTFILE);
end

PARAMS = nscan_loadtxt(TXTFILE);

% if any(regexpi(TXTFILE,'.dap$'))
%   PARAMS = sub_proc_dap(PARAMS);
% elseif any(regexpi(TXTFILE,'.rs3$'))
%   PARAMS = sub_proc_rs3(PARAMS);
% elseif any(regexpi(TXTFILE,'.ceo$'))
%   PARAMS = sub_proc_ceo(PARAMS);
% end

[fp, fr, fe] = fileparts(TXTFILE);
switch lower(fe)
 case {'.dap'}
  PARAMS = sub_proc_dap(PARAMS);
 case {'.rs3'}
  PARAMS = sub_proc_rs3(PARAMS);
 case {'.ceo'}
  PARAMS = sub_proc_ceo(PARAMS);
 otherwise
  % keep as it is (no string conversion)
end

return


% =======================================================
function PARAMS = sub_proc_dap(PARAMS)
% =======================================================
% convert into numerics, if possible
if isfield(PARAMS,'DATA_PARAMETERS')
  fnames = {...
      'NumSessions',...
      'CurrentSession',...
      'FrequencyDomain',...
      'NumSamples',...
      'NumTrials',...
      'NumChannels',...
      'NumGroups',...
      'NumMagGroups',...
      'NumElGroups',...
      'IntOffset',...
      'NumLinesSkip',...
      'NumColumnsSkip',...
      'DecimalSymbol',...
      'DigLengthUnit',...
      'DigColX',...
      'DigColY',...
      'DigColZ',...
      'DigColLabel',...
      'DigDirX',...
      'DigDirY',...
      'DigDirZ',...
      'StartYear',...
      'StartMonth',...
      'StartDay',...
      'StartHour',...
      'StartMin',...
      'StartSec',...
      'StartMillisec',...
      'SampleTimeUsec',...
      'SampleFreqHz',...
      'TriggerOffsetUsec',...
      'TriggerOffsetHz',...
      'StimIntervalUsec',...
           };
  
  PARAMS.DATA_PARAMETERS = nscan_strconv(PARAMS.DATA_PARAMETERS,...
                                          'str2num','fields',fnames);
end

if isfield(PARAMS,'DEVICE_PARAMETERS')
  fnames = {...
      'SensorSourceThisGroup',...
      'NumChanThisGroup',...
      'NumSensorsThisGroup',...
      'CommonOffset',...
      'NumRefChannels',...
      'CommonScale',...
           };
  PARAMS.DEVICE_PARAMETERS = nscan_strconv(PARAMS.DEVICE_PARAMETERS,...
                                            'str2num','fields',fnames);
end

if isfield(PARAMS,'DEVICE_PARAMETERS_OTHERS')
  fnames = {...
      'SensorSourceThisGroup',...
      'NumChanThisGroup',...
      'NumSensorsThisGroup',...
      'CommonOffset',...
      'NumRefChannels',...
      'CommonScale',...
           };
  PARAMS.DEVICE_PARAMETERS_OTHERS = nscan_strconv(PARAMS.DEVICE_PARAMETERS_OTHERS,...
                                                   'str2num','fields',fnames);
end

if isfield(PARAMS,'CHAN_IN_FILE')
  PARAMS.CHAN_IN_FILE = nscan_strconv(PARAMS.CHAN_IN_FILE,'numlist');
end
  
if isfield(PARAMS,'CHAN_IN_FILE_OTHERS')
  PARAMS.CHAN_IN_FILE_OTHERS = nscan_strconv(PARAMS.CHAN_IN_FILE_OTHERS,'numlist');
end

if isfield(PARAMS,'TRIGGER_FLAGS_OTHERS')
  PARAMS.TRIGGER_FLAGS_OTHERS = nscan_strconv(PARAMS.TRIGGER_FLAGS_OTHERS,'numlist');
end
  
return


% =======================================================
function PARAMS = sub_proc_rs3(PARAMS)
% =======================================================
% convert into numerics, if possible
if isfield(PARAMS,'NUMBERS')
  PARAMS.NUMBERS = nscan_strconv(PARAMS.NUMBERS,'numlist');
end

if isfield(PARAMS,'LABELS')
  PARAMS.LABELS = nscan_strconv(PARAMS.LABELS,'strlist');
end

if isfield(PARAMS,'GEOMETRY')
  fnames = {...
      'HelmetSystem',...
      'PlanarSensors',...
      'SensorShape',...
      'SensorOrder',...
      'SensorStatus',...
      'SensorDiameterXMm',...
      'SensorDiameterYMm',...
      'SystemCenterXMm',...
      'SystemCenterYMm',...
      'SystemCenterZMm',...
      'BaselengthMm',...
           };
  PARAMS.GEOMETRY = nscan_strconv(PARAMS.GEOMETRY,'str2num','fields',fnames);
end

if isfield(PARAMS,'SENSORS')
  PARAMS.SENSORS = nscan_strconv(PARAMS.SENSORS,'numlist');
end

if isfield(PARAMS,'TRANSFORM')
  PARAMS.TRANSFORM = nscan_strconv(PARAMS.TRANSFORM,'numlist');
end

if isfield(PARAMS,'NUMBERS_OTHERS')
  PARAMS.NUMBERS_OTHERS = nscan_strconv(PARAMS.NUMBERS_OTHERS,'numlist');
end

if isfield(PARAMS,'LABELS_OTHERS')
  PARAMS.LABELS_OTHERS = nscan_strconv(PARAMS.LABELS_OTHERS,'strlist');
end

return


% =======================================================
function PARAMS = sub_proc_ceo(PARAMS)
% =======================================================
% convert into numerics, if possible
if isfield(PARAMS,'POINT_KEYWORDS')
  fnames = {...
      'PointNrLocations',...
      'PointNrTimepts',...
      'PointType',...
      'PointCoordSystem',...
      'PointTypeSamples',...
      'PointPlotFlags',...
      'PointPlotFlagsEx',...
      'PointPlotColor1',...
      'PointPlotColor2',...
      'PointPlotColor3',...
      'PointPlotShape',...
      'PointPlotSurface',...
      'PointPlotTranspa',...
      'PointPlotClipping',...
      'PointPlotTextsize',...
      'PointPlotBorder',...
      'PointPlotAdjacent',...
      'PointPlotClosed',...
      'PointPlotType1',...
      'PointPlotType2',...
      'PointPlotType3',...
      'PointPlotInflations',...
      'PointPlotInfwanted',...
      'PointPlotRepaired',...
      'PointTFirst',...
      'PointTDelta',...
      'PointDistance',...
      'PointArea',...
      'PointVolume',...
      'PointSymbolsize',...
      'PointLinewidth',...
      'PointPlotDist1',...
      'PointPlotDist2',...
      'PointPlotDist3',...
           };

  PARAMS.POINT_KEYWORDS = nscan_strconv(PARAMS.POINT_KEYWORDS,'str2num','fields',fnames);
end


if isfield(PARAMS,'POINT_DESCRIPTION')
  fnames = {...
           };
  
  PARAMS.POINT_DESCRIPTION = nscan_strconv(PARAMS.POINT_DESCRIPTION,'str2num','fields',fnames);
end


if isfield(PARAMS,'LOCATION_LIST')
  PARAMS.LOCATION_LIST = nscan_strconv(PARAMS.LOCATION_LIST,'numlist');
end


if isfield(PARAMS,'NUMBER_LIST')
  PARAMS.NUMBER_LIST = nscan_strconv(PARAMS.NUMBER_LIST,'numlist');
end

if isfield(PARAMS,'REMARK_LIST')
  % not for sure...
  %PARAMS.REMARK_LIST = nscan_strconv(PARAMS.REMARK_LIST,'strlist');
  %PARAMS.REMARK_LIST = nscan_strcon(PARAMS.REMARK_LIST,'numlist');
end


return
