function GROI = macaque_henry(varargin)
%MACAQUE_HENRY - Returns the ROIs of the macaque monkey - 2012-March-06
%
%  EXAMPLE :
%    groi = macaque_henry;
%    groi = rat_henry;
%
%  See also rat_henry paxroigroups

if nargin==0 & nargout==0,
  % PRINT OUT INFO ABOUT THE MONKEY ROIs
  anap = getanap('e10gb1'); roi = anap.SELROI;
  GROI = macaque_henry;
  for N=1:length(GROI),
    TMP{N}=GROI{N}{1};
  end;
  idx = [];
  for N=1:length(roi),
    idx(N) = find(strcmpi(roi{N},TMP));
  end;
    
  for J=1:length(GROI);
    if J>length(roi), continue; end;
    N = idx(J);
    txt1 = sprintf('%s ', GROI{N}{2});
    
    fprintf('%2d\t%-14s\t%-30s\n', J, GROI{N}{1}, txt1);
    continue;
    if length(GROI{N})>3
      txt2 = GROI{N}{4};
      txt2 = sprintf('%s ', txt2{:}); txt2=txt2(1:end-1);
      fprintf('%-14s %-30s %-40s\n', GROI{N}{1}, txt1, txt2);
    else
      fprintf('%-14s %-30s\n', GROI{N}{1}, txt1);
    end;
  end;
  return;
end;


GROI = {};
%======================Henry started on 2012-Jan-23========================
%===================Updated on 2013-Feb-12 to match rat ROI================
% Non-exhaustive list of regions of interest. For clarity and future
% extension/grouping; structures are listed by division (rhombencephalon
% to diencephalon) and subdivision. Names are all from Paxinos Macaque Atlas.
%
%===================Updated on 2014-Aug-3 to add V1 and NBM================
% (1) Three new ROI's were created within V1: foveal, parafoveal and peripheral
% (fV1, pfV1, pV1) based on Van Essen et al. (1984).
% (2) The nucleus basalis of Meynert was added (NBM).
% (3) Removed oboslete "Olf" and "Striatum".


% Major fiber tracts:     
% GROI{end+1} =  {'CC', 'CorpCalos', [.2 .2 .2], {'cc','f','vhc','rcc','SS'}};
% GROI{end+1} =  {'ac', 'AntComm', [0.49 0.00 0.20], {'aca','acp'}};
% GROI{end+1} = {'nerve' 'Nerve' [0.33 0.04 0.39] ...
%                { 'asc7' '8cn' 'g7' '9n' '3n' '2n' 'Op' 'ox' ...
%                  '6n' '12n' '4n' '10n' '8n' } };
% GROI{end+1} = {'tract' 'Tract' [0.49 0.06 0.39] ...
%               { 'ctg' 'dsc' 'lo' 'ltg' 'lvs' 'lvsp' ...
%                 'mt' 'me5' 'py' 'rs' 'sol' 'sp5' 'spth' ...
%                 'tth' 'vcsp' 'vsc' 'veme' } };
% Major blood arteries/veins:
% GROI{end+1} =  {'ArtVein', 'Arteries and Veins', [0 0.5 0],...
%                 { 'azac' 'acer' 'a' 'bas' 'cala' 'dcba' 'ictd' ...
%                   'lga' 'lscb' 'mcer' 'mscb' 'pcom' 'pica' 'tep' 'v'}};
%
% RHOMBENCEPHALON (Brainstem)++++++++++++++++++++++++++++++++++++++++++++
% All small structures (mainly cranial nerve nuclei and brainstem reticular
% formation like the gigantocellular reticular nucleus, Gi)

GROI{end+1} =  {'ParabrachialN', 'PBn', [0.31 0.22 0.78]};

GROI{end+1} =  {'Brainstem', 'Brainstem', [0.31 0.22 0.78],...
                {'3N','3PC','EW',...
                 '6N','12N',...
                 'DMSp5','DMSp5D','Ge5',...
                 '7D','7D/L','7DI','7DL','7DM','7I','7L','7N','7V','7VI','7VM','Acs7',...
                 'MVeMC','MVePC','SuVe','DPGi','Gi',...
                 'Ca','CaI','DoR',...
                 'ECu','Gr',...
                 'FVe'}};

% METENCEPHALON (PONS + CEREBELLUM)++++++++++++++++++++++++++++++++++++++++
% Cerebellum (dorsal met.)-------------------------------------------------
% proximal muscles - trunk/posture - spinocerebellum proximal
GROI{end+1} =  {'Vermis','Vermis', [0.57 0.06 0.20], {'vermis'}};                  
% proximal muscles - trunk/posture - spinocerebellum proximal
GROI{end+1} =  {'alCb','Anterior cerebellar lobe', [0.63 0.06 0.78],...
                {'alCb'}};
% distal muscles - limbs - spinocerebellum distal
GROI{end+1} =  {'IntHemCb','Intermediate cerebellar hemisphere', [0.59 0.06 0.39],...
                {'inthemCb'}};                                            
% receive cortical afferent from the pontine nucleus - cerebrocerebellum
GROI{end+1} =  {'LatHemCb','Lateral cerebellar hemisphere', [0.61 0.06 0.59],...
                {'lathemCb'}};                                           
% receive vestibular afferent - vestibullo/oculocerebellum 
GROI{end+1} =  {'pflCb','Parafloculonodular', [0.90 0.22 0.78],...
                {'pflCb'}};                                               
% output of the cerebellum - massive projections to thalamus (+few others)
GROI{end+1} =  {'DCbN', 'Deep cerebellar nuclei', [.2 .2 1],...
                {'DCbN'}};                                                

% Pons (ventral met.)------------------------------------------------------
% pontine nuclei complex
% Relays of neorcortical afferent to the cerebellar cortex and nuclei.
% The pontine fibers that enter the cerebellum are called the "mossy
% fibers".
GROI{end+1} = {'PontReg','Pontine Region',[0.60 1.00 0.00],...
               {'PontReg',...
                'DMPn','DPPn','gamma','Pn','tfp','lfp',...
                'PnC','PnO','PnV','PnR','RtTg','RtTgL'}};
% Raphe (serotoninergic projection - neuromodulatory)
GROI{end+1} =  {'Raphe', 'Raphe', [.2 .2 1],...
                {'RIP','RMg','ROb','RPa','CLi','DR','DRC','DRD','DRI',...
                 'DRV','DRVL','PMnR','RLi','MnR','PnR','RIP','RMg',...
                 'ROb','RPa','Raphe'}};
% Locus Coeruleus Region 
GROI{end+1} =  {'LC_CGn', 'Locus Coeruleus + Central Gray', [.2 .2 1],...
                {'LC','CGpn'}};
% GROI{end+1} =  {'InfOl',  'Inferior Olive', [0.22 0.00 0.39],...
%                {'ami','CPO','DPO','IOA','IOB','IOM','IOC','IOPr','IOVL'}};
% GROI{end+1} =  {'IP', 'IntPedunc', [.1 .2 .3],...
%                {'IP','IPC','IPL','IPR'}};
% GROI{end+1} =  {'PnRet','Pontine Reticular nucleus',  [0.04 0.25 0.78],...
%                {'PnC','PnO','PnV','PnR','RtTg','RtTgL'}};
% GROI{end+1} =  {'Pn',  'Pontine nucleus', [0.12 0.10 0.39],...
%                {'DMPn','DPPn','gamma','Pn','tfp','lfp'}};
% GROI{end+1} =  {'Pons','Pons',[.7 .7 .7],...
%                {'lfp','Pn','PnC','PnO','PnV','PnR','RtTg','RtTgL',...
%                 'lfp','tfp'}};

% MESENCEPHALON++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% MesE = Mesencephalon
% APT - Anterior Pretectal Nucleus
% RPC - Red Nucleus Parvocellular Part 
GROI{end+1} =  {'MesE','MesE',[.2 .2 .2],...
                {'APT','IMLF','IMLFG','m1','PaR','REth','RMC','RPC'}};
% Tectum (Inf and Sup Col)-----------------------------------------------
GROI{end+1} =  {'SC', 'Superior Colliculus',      [.4 .3 .1],...
                {'DpG','DpWh',...
                 'InG','InWh','Op','SuG','SC','Zo','bsc','csc'}};
GROI{end+1} =  {'InfCol',  'Inferior Colliculus', [0.08 0.22 0.39],...
                {'InfCol','BIC','CIC','cic','ECIC','IC','DCIC','bic'...
                 'PBG'}};
% GROI{end+1} =  {'PreTect','Pretectum',            [0.27 0.22 0.39],...
%                 {'OPT',optic tract nucleus,a,m,post medial pretectal'}

% Tegmentum--------------------------------------------------------------
% Lateral tegmental area:
% GROI{end+1} =  {'LatTeg', 'Lateral Tegmental Area', [0.71 0.08 0.98],...
%                {'DPGi','A5','A7'}};

% Dorsal tegmental area:
% GROI{end+1} =  {'DorsTeg', 'Dorsal Tegmental Area', [0.96 0.08 0.59],...
%                {'DTg','DTgC','DTgP','dtgx','dtg'}};

GROI{end+1} =  {'PAG', 'Periaqueductal Gray', [.5 .5 .5],...
                {'DLPAG','DMPAG','LPAG','PAG','Su3','Su3C','VLPAG'}};

% GROI{end+1} =  {'CentGray', 'Central Gray', [0.41 0.06 0.59],...
%                {'CGpn'}};

% DIENCEPHALON+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
% Basal Forebrain----------------------------------------------------------
GROI{end+1} =  {'MSDB', 'Diagonal Band + Septum', [.3 .5 .7],... %IMO, too small to be drawn spearately, like in monkeys
                {'HDB','VDB','LS','LSD','LSV','LSI','MS','Ld','PLd',...
                 'Spt','SFi','SHi','SHy'}};
%GROI{end+1} =  {'DB', 'Diagonal Band', [0.10 0.22 0.59], {'HDB','VDB'}};
%GROI{end+1} =  {'Septum', 'Septum', [.2 1 .2],...
 %               {'LS','LSD','LSV','LSI','MS','Ld','PLd',...
 %               'Spt','SFi','SHi','SHy'}};
GROI{end+1} =  {'BNST', 'Stria_Terminalis+Meynert+Sub_Innominata', [.5 0 0],...
               {'BST','BSTIA','BSTL','BSTLJ','BSTLD','BSTLI' 'BSTLP',...
                'BSTM' 'BSTMA','BSTMP','BSTMPI','BSTMPL','BSTMPM','BSTMV','SI#2','SIB','B','BM#4' }};
GROI{end+1} =  {'NBM', 'Nucleus Basalis Meynert', [0.10 0.22 0.59], {'NBM'}};

% Basal Ganglia------------------------------------------------------------ 
% SN could be placed in 'rostral mesencephalon'
% GROI{end+1} =  {'BG', 'BG', [.5 .8 1],...
  %              {'BG'}};
%GROI{end+1} =  {'Striatum', 'Striatum', [.5 .8 1],...
                %{'Cd','Pu','VP','E','CB','VP#3','Acb','AcbC', 'AcbSh','LAcbSh','ICj','ICjM'}};  
GROI{end+1} =  {'VS', 'Ventral Striatum', [.1 .2 1],...
                {'Pu','VP','E','CB','VP#3','Acb','AcbC', 'AcbSh','LAcbSh','ICj','ICjM'}};
GROI{end+1} =  {'DS', 'Dorsal Striatum', [.5 .8 1],...
                {'Cd','Pu'}};
GROI{end+1} =  {'GP',  'Globus Pallidus', [.5 .8 1],...
                {'EGP','IGP'}}; 
%GROI{end+1} =  {'Acb', 'Accumbens', [1 0 0],...
 %               {'Acb','AcbC', 'AcbSh','LAcbSh','ICj','ICjM'}}; WAS MOVED
 %               TO STRIATUM 2012-March-06
GROI{end+1} =  {'SN','Substantia Nigra',[.3 .1 .6],...
                {'SN','SND','SNL','SNM','SNR','SNVM','SNVL',...
                'SNV' 'SNC' 'SNCV' }};          
GROI{end+1} =  {'VTA','Ventral Tegmental Area', [.4 .6 1], {'VTA'}};      

% Smaller and 'hard to map' regions------------------------------------------
% GROI{end+1} =  {'ZoIns','Zona Inserta', [.7 .5 .3], {'ZI','ZID','ZIV','ZIR'}};
% GROI{end+1} =  {'IPAC', 'Ipac',[0.73 0.14 0.39], {'IPAC','IPACL','IPACM'}};
% GROI{end+1} =  {'SubInn','Substantia Innominata',[.4 1 .4], {'SI#2','SIB','B','BM#4'}};

%Hypothalamus------------------------------------------------------------
GROI{end+1} =  {'HTh', 'Hypothalamus', [0 .5 0]...
                {'SV','SCh','AMPO','SV','AVPe',...
                 'MnPO','MPA','MPOL','MPOM','LPO','ADP',...
                 'SChV','SChD','LTer',...
                 'AHA','AHC','AHP',...
                 'DM','DMC','DMD','DMV',...
                 'DH',...
                 'Gem',...
                 'MCLH' 'PaAM' 'PaAP' 'PaMD' 'PaPo' 'Pe' 'PH' ...
                 'VLH' 'VMH' 'VMHC' 'VMHDM' 'VMHVL' 'ArcD' 'ArcL' 'ArcM' }};
% Amygdala---------------------------------------------------------------
GROI{end+1} =  {'Amy', 'Amygdala', [.8 0 0],...
                {'AA','AAV','AAD','AHi','AHiMC','AHiPC','AHiPM','BL','BLD','BLDL',...
                 'BLI','BLV','BLVL','BLVM','BM','BMMC','BMPC','BMPCD',...
                 'BMPCV','BMPCVM','Ce','CeC','CeCv','CEm#1','BLP',...
                 'CeL','CeM','CeMD','CeMV','I','IMG',...
                 'La','LaDL','LaVL','LaVM','Me','MeMV','PaL','PaLGl',...
                 'VACo','VCo','VCoIn','VCoInf','VCoSu','APir','EA',...
                 'I#2','La#3'}};
GROI{end+1} =  {'basalAmy', 'Basal Amygdala', [.8 0 0],...
                {'BL','BLD','BLDL'}}; %Added on 2012-08-17
% Hippocampus------------------------------------------------------------
GROI{end+1} =  {'HP', 'Hippocampus',              [1 0 0],...
                {'Hip' 'CA1^' 'CA1','CA2','CA3','CA4','fi','PaS','PrS','S','ProS',...
                 'DG','PoDG','GrDG','AHi','Or'}};            

% Thalamus---------------------------------------------------------------
GROI{end+1} =  {'Tha', 'Thalamus',                [1 .8 .5],...
                {'Rt',...
                 'AD','AM','AMV','AV','IAM','AD#1','AM#1',...              % Anterior (striatum)
                 'VAM','VAMC','VAL(VO)+pal','VAL(VO)','VAL(pal)'...        % Anterior (striatum)
                 'VPL','VPM',...                                           % Sensory (spinal)
                 'VLL','VLM','VLM#1','VLPE','VLPI',...                     % Motor (cerebellar)
                 'LDSF','LDTg','LDTgV',...                                 % Lateral dorsal
                 'CL','CM#2','PF','PF#2','CMn','CMnM','CMnL','PC','CL#2',... % Intralaminar
                 'MD','IMD','MDC','MDM','MDL','MDD',...                    % Mediodorsal (PFC)
                 'PV','PVA','PVP','PT','Re',...
                 'Gus',...
                 'Ang',...
                 'IAD','IAM',...
                 'SG',...
                 'SPF','SPFC','Xi','mt',...
                 'eml','iml','ithp','PLi','PoMn',...
                 'VPI','VPPC','VPL#1','VM'}};

GROI{end+1} =  {'Pul', 'Pulvinar n',                [0.43 0.25 0.78],...
                {'APul','IPul','MPul','LPul','Pul'}};
GROI{end+1} =  {'LGN', 'Lateral Geniculate n',                [0.43 0.25 0.78],...
                {'DLG','PrG' 'LGN' '$1' '$2' '$3' '$4' '$5' '$6' 'VLG' }};

% GROI{end+1} =  {'MGN','MGN',[.4 .4 .4], {'MGD','MGV','MGM'}};
% Included in 'Tha'

%Claustrum---------------------------------------------------------------
%GROI{end+1} =  {'Claustrum','Claustrum', [0.90 0.06 0.59],...
 %               {'Cl'}};

% TELENCEPHALON - CORTICAL++++++++++++25 GROI's+++++++++++++++++++++++++++
%GROI{end+1} =  {'Olf','Olfactory',[ .3 .3 .3],...
                %{'AO','AOM','AOL','Tu',...
                % 'Olb'}}; 
GROI{end+1} =  {'Ent', 'Entorhinal Cortex',      [0 1 0],...
                {'DEn','Ect','LEnt','PRh','VEn','MEnt','35',...
                 'EC#2','ECL','EI','EL','ELC','ELR','Ent','EOI','ER#1'}};
GROI{end+1} =  {'PirFo','Piriform Cortex',[.1 .5 .1],...
                {'Pir','VCoSu','VCoInf','VCoIn','VEn','DEn'}};

% Sensorimotor Areas (premotor, motor, somatosensory)--------------------
GROI{end+1} =  {'Premotor','Premotor Cortex', [0.96 0.02 0.39],...
                {'6','6DR(F7)','6M','6DC(F2)','6VC(F4)','6VR(F5)','6VV'}};
GROI{end+1} =  {'Motor','Motor Cortex', [0.67 0.02 0.39], {'4','4(F1)','4#1','4C'}};
GROI{end+1} =  {'S1', 'Primary Somatosensory Cortex', [1 0 1],...
               {'1#1','2#1','2/1','3a','3b'}};
GROI{end+1} =  {'S2', 'Other Somatosensory Cortices', [1 0 1],...
                {'S2','S2E','S2I','ReI','ReIT','ReIP','PGOp' '2Ve'}};

% Insular Areas-----------------------------------------------------------
GROI{end+1} =  {'Ins', 'Insular Cortex', [.7 1 .5],...
                {'IPro','AI','DI','GI','OPro','Gu','DI#2','ProI'}};
GROI{end+1} =  {'aIns', 'Anterior Insular Cortex', [.7 1 .5],...
                {'AI'}}; %Added on 2012-08-17

% Cingulate Areas (Anterior, Posterior, Retrosplenial)--------------------
GROI{end+1} =  {'ACC','Anterior Cingulate Cortex', [1 0 0],...
                {'9/32','24a','24b','24c','24d','8/32','6/32'}};
GROI{end+1} =  {'dACC','Dorsal Anterior Cingulate Cortex', [1 0 0],...
                {'24a','24b'}};           
GROI{end+1} =  {'PCC','Posterior Cingulate Cortex', [1 0 0],...
                {'24/23','24/23a','24/23b','24/23c',...
                 '23','23a','23b','23c','23d','23x'}};
GROI{end+1} =  {'RetroSp','Retrosplenial Cortex', [0.49 0.02 0.98],...                
                {'29a-c','29d','29a','29a-d','29','30'}};

% Prefrontal Areas (orbital, medial, dorsolateral)------------------------
GROI{end+1} =  {'orbPFC','Orbital Prefrontal Cortex', [.5 .5 0],...
                {'14M','14O','11','11M','11L',...
                 '13','13a','13M','13L',...
                 '47','47L','47O','ProM','proM#1',...
                 '47(12)','47(12)L','47(12)O',...
                 'OPAl'}};
GROI{end+1} =  {'medPFC','Medial Prefrontal Cortex', [1 .4 .4],...
                {'10M','10D','10V','32','25','IG','10','10L'}};
GROI{end+1} =  {'dlPFC','Dorsolateral Prefrontal Cortex', [0.10 0.04 0.98],...
                {'9M','9L','9/46D','9/46','46D','46V','9/46V','46',...
                 '45A','45B','44',...
                 '8A','8B','8AD','8AV'}};
             
% Visual Areas-------------------------------------------------------------
GROI{end+1} =  {'V1','Primary Visual Cortex', [0 1 0], {'V1' 'V1B','V1M'}};
GROI{end+1} =  {'fV1','Foveal Primary Visual Cortex', [0 1 0], {'V1' 'V1B','V1M'}};
GROI{end+1} =  {'pfV1','Parafoveal Primary Visual Cortex', [0 1 0], {'V1' 'V1B','V1M'}};
GROI{end+1} =  {'pV1','Peripheral Primary Visual Cortex', [0 1 0], {'V1' 'V1B','V1M'}};
GROI{end+1} =  {'V2V3','V2V3', [0 1 0],...
                {'V2','V3','V3V','V3D','V3A'}};
GROI{end+1} =  {'V4','V4', [0.27 0.35 0.20],...
                {'V4','V4A' 'V4D','V4V','JxST','ProSt','V4T'}}; 
GROI{end+1} =  {'V5','V5', [0.35 0.20 0.78],...
                {'MT(V5)','MST'}};     
            
%Auditory Areas------------------------------------------------------------
GROI{end+1} =  {'TmpAu','Auditory Tempora lCortex', [0 .5 0],...
                {'AKL','AKM',...                                           % Primary auditory                         
                 'PaAC','PaAL','PaAR',...                                  % Para-lateral
                 'PaIL','PaIM','ProKM','ProKL','PaI','ProK'}};

% Temporal Associative-----------------------------------------------------
GROI{end+1} =  {'TmpPol','Polar Temporal Cortex', [0 .5 0],...
                {'TPPro','TTPAl','TPAl'}};   
GROI{end+1} =  {'TmpSTS','Superior Temporal Sulcus', [0.80 0.41 0.59],...
                {'ST2','ST1','ST2S','ST2G','ST3',...
                 'TPO','PGa','TAa','TPt','FST'}};
GROI{end+1} =  {'TmpVis','Inferior Temporal Sulcus', [0.41 0.31 0.78],...            
                {'TE1#1' 'TE1L' 'TE1M' ...
                 'TE2#1' 'TE2L' 'TE2M' ...
                 'TE3#1','TEa#1','TFL','TFM','TEO','TEOM',...
                 'TF','TFO','TEM','IPa','PGa'}};
% GROI{end+1} =  {'TmpMed','Temporal Medial', [0.67 0.31 0.39],...
                % {'TLO(36O)','TLR(R36)','TH','THO','36O','TL(36)','TLO'}};
                % USUALLY IN THE EAR CANAL VOID

% Parietal Associative------------------------------------------------------
GROI{end+1} =  {'ParLat','Parietal Lateral', [.5 0 0],...
                {'PG','PGOp','DPt','OPt','PPt','PFOp','PFCx','PFG#1','PG'}};
GROI{end+1} =  {'ParIntra','Intraparietal', [0.53 0.24 0.39],...             
                {'PE','PE#1','POaE','POaI','POa','PEa','Pea','DIP' 'LIP', ...
                 '(LIP)' 'LIPE' 'LIPI','(VIP)'}};        
                % Corresponds also to 7m (Parvizi et al. PNAS 2006) of the larger 
                % posteromedial cortex (Precuneus+Retrosplenial)
GROI{end+1} =  {'ParPrec','Parietal Precuneus', [0.35 0.24 0.59],...
                {'PEC','PGM','PECg','PO','31','PGM/31','PO#1'}};

      



