function depload(SESSION,ExpNo)
%DEPLOAD - Reads the contrast functions saved in the Contrasts directory
% DEPLOAD (SESSION,ExpNo) will read all contrast generated by
% confunc and saved in the SESSION/Contrast directory.
% NKL, 10.10.02

Ses = goto(SESSION);
filename = catfilename(Ses,ExpNo,'dep');

s = load(filename);
snames = fieldnames(s);

for N=1:length(snames),
  assignin('caller', snames{N}, eval(sprintf('s.%s',snames{N})));
end;
