function clnhelp
%CLNHELP - Denoising process for fMRI/Physiology Experiments
%	CLNHELP lists the steps required to remove the interference
%	generated by the alternation of the imaging field gradients.
%	Usually the entire process will be carried out by
%	sesclnmain(SesName). For data sets that are not denoised
%	appropriate through the automatic process the following steps permit
%	an interactive cleaning of the physiology signal.
%
%	=========================================================================
%	PROCESS:
%	=========================================================================
%	1. sesinfo(SesName)			Provides information (in case of debugging)
%	2. getclockerror(SesName,ExpNo) Get QNX clock error (optional)
%	3. clnadjevt(SesName,ExpNo)	Adjusts the events, creates ClnAdjEvt.mat
%	4. clnmain(SesName,ExpNo)	Cleans the data
%	
%	See also HNEUPRO
%
%	Utilities
%	=========================================================================
%	CLNHELP - This file
%	SESINFO - Display imaging/physiology information for session
%	GETCLOCKERROR - Compute difference between QNX/Paravision clocks
%
%	Functions to do the actual denoising
%	=========================================================================
%	CLNADJEVT - Fixup the random deviations of MRI events
%	CLNMAIN - Main program to denoise the physiology signal
%	CLNADF - Actual cleaner

helpwin clnhelp





