function stmpars = mlstm_read(stmfile,varargin)
%MLSTM_READ - Get stimulus parameters from the stmfile generated by ICPBR-MonkeyLogic.
%  STMPARS = MLSTM_READ(STMFILE,...) reads stimulus parameters from the stmfile generated by
%  ICPBR-MonkeyLogic.
%  Supported options are
%    'verbose'  :  0|1, verbose or not.
%
%  EXAMPLE :
%    stmpars = mlstm_read('E:\DataMri\20250821_141618_NikosGroup_Phantom_20250821a_2_2\stmfiles\A23_250821_1519_MriGeneric.stm')
%
%  VERSION :
%    0.90 26.08.25 YM  pre-release.
%
% See also expgetpar expmlgetevt txt_read

if nargin < 1, help mlstm_read; return;  end

% initialize output
stmpars = [];


VERBOSE = 1;
NO_COMMENT = 1;
for N = 1:2:length(varargin),
  switch lower(varargin{N}),
   case {'verbose'}
    VERBOSE = varargin{N+1};
   case {'nocomment','no comment'}
    NO_COMMENT = varargin{N+1};
   case {'comment','comments'}
    NO_COMMENT = ~varargin{N+1};
  end
end

if isempty(stmfile),
  [stmfile, pathname] = uigetfile(...
      {'*.stm', 'STM Files (*.stm)'; ...
       '*.*',   'All Files (*.*)'}, ...
      'Pick a stm file',pwd);
  if isequal(stmfile, 0) || isequal(pathname,0), 
    fprintf(' %s: uigetfile() canceled.\n',mfilename);
    return;
  end
  stmfile = fullfile(pathname,stmfile);
  clear pathname;
end


if ~exist(stmfile,'file'),
  if VERBOSE,
    fprintf(' WARNING %s: ''%s'' not found.\n',mfilename,stmfile);
  end
  return;
end

% read lines %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% load the file
texts = {};
fid = fopen(stmfile,'r');
while 1,
  if feof(fid),  break,  end;
  texts = cat(2,texts,fgetl(fid));
end
fclose(fid);
% remove comments, spaces etc.
lines = {};
for N = 1:length(texts),
  tmpline = strtrim(deblank(texts{N}));
  if isempty(tmpline), continue;  end
  if NO_COMMENT,
    % remove comments following '#'
    if tmpline(1) == '#', continue;  end
    if tmpline(1) == '%', continue;  end
  end
  lines = cat(2,lines,tmpline);
end

% make a pars-struct of stimuli
for N = 1:length(lines),
  [parname,parvalue] = subGetPars(lines{N});
  if isempty(parname), continue;  end
  switch parname
   case { 'NumTrigPerVolume' }
    stmpars.NumTrigPerVolume = str2double(parvalue);
   case { 'N_Conditions' }
    stmpars.N_Conditions = str2double(parvalue);
   case { 'N_TrialRepeats' }
    stmpars.N_TrialRepeats = str2double(parvalue);
   case { 'FUNC_MakeStimulus'}
    stmpars.FUNC_MakeStimulus = parvalue;  
   case { 'STIM_TYPES' }
    stmpars.StimTypes  = {};
    stmpars.StimObjIDs  = {};
    stmpars.StimGrp     = [];
    rem = parvalue;
    curstmgrp = 0;
    curstmid  = 0;
    while 1,
      [token,rem] = strtok(rem);
      if ~isempty(token),
        if token(1) == '{',
          idx = strfind(rem,'}');
          tmprem = rem(1:idx(1)-1);
          rem = rem(idx(1)+1:end);
          token = token(2:end);
          token = strrep(token,' ',''); % remove blanks
          tmptypes = {};
          while 1,
            [token,tmprem] = strtok(tmprem);
            if ~isempty(token),
              tmptypes = cat(2,tmptypes,token);
              %tmptypes{end+1} = token;
            end
            if isempty(tmprem),  break;  end
          end
          tmpstr = sprintf('%s',tmptypes{1});
          for K = 2:length(tmptypes),
            tmpstr = sprintf('%s+%s',tmpstr,tmptypes{K});
          end
        else
          tmpstr   = token;
          tmptypes = { token };
        end
        stmpars.StimTypes{end+1}  = tmpstr;
        stmpars.StimObjIDs{end+1} = (0:length(tmptypes)-1) + curstmid;
        stmpars.StimGrp(end+1)    = curstmgrp;
        curstmid  = curstmid  + length(tmptypes);
        curstmgrp = curstmgrp + 1;
      end
      if isempty(rem), break; end
    end
   case { 'STIM_VOLUMES' }
    stmpars.StimDurations = str2num(parvalue);
   otherwise
  end
end


return;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [parname,parvalue] = subGetPars(txtline)
parname = '';  parvalue = '';
k = strfind(txtline,';');
if ~isempty(k)
  txtline = txtline(1:k-1);
end

[token,rem] = strtok(txtline,'=');
parname = strip(token);
parvalue = strrep(strip(rem(2:end)),'''','');

if isempty(parvalue), return;  end
if strcmp(parvalue(1),'{')
  % check complete end of '{'
  k = strfind(parvalue,'}');
  if ~isempty(k)
    parvalue = parvalue(1:k);
  end
elseif strcmp(parvalue(1),'[')
  k = strfind(parvalue,']');
  if ~isempty(k)
    parvalue = parvalue(1:k);
  end
end
